version: '3.8'
services:
  blackjack-app:
    build: .
    depends_on:
      - mysql
      - mongo
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/blackjack
      SPRING_PROFILES_ACTIVE: prod
      SPRING_R2DBC_URL: r2dbc:mariadb://mysql:3306/blackjack
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: pass

  mysql:
    image: mariadb:10.11  # Cambiar a MariaDB
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: blackjack
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command:
      - --init-file
      - /docker-entrypoint-initdb.d/schema.sql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped